apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-ingress
spec:
  rules:
    - host: foo.jomo.click
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: foo-app-service
                port:
                  number: 3000
    - host: bar.jomo.click
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bar-app-service
                port:
                  number: 3000
  tls:
    - hosts:
        - foo.jomo.click
        - bar.jomo.click
      secretName: tls-keys

